src/conclave/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import current_user, login_required
from src import app, db
from src.models import Topic, Category, User, Reply
from src.conclave.forms import NewTopicForm, ReplyTopicForm, EditTopicForm, AddCategoryForm
import datetime
from sqlalchemy.sql.functions import func

conclave = Blueprint('conclave', __name__,
                     template_folder='templates/forum')


@conclave.route('/')
def index():
    # topics = Topic.query.all()
    categories = Category.query.all()
    # replies = db.session.query(Topic, func.count(Reply.reply_topic)).outerjoin(Topic, Reply.reply_topic == Topic.id)\
    #     .group_by(Topic.topic_title).all()
    topics = db.session.query(Topic.id, Topic.topic_title, Topic.topic_category, func.count(Reply.reply_topic)
                              .label('count_1')).outerjoin(Topic, Reply.reply_topic == Topic.id).group_by(Topic.topic_title).all()

    return render_template('main.html', topics=topics, categories=categories)


@conclave.route('/category/<int:category_id>')
def category_view(category_id):
    category = Category.query.filter_by(id=category_id).first()
    topics = Topic.query.filter_by(topic_category=category_id).all()
    replies = db.session.query(Topic, func.count(Reply.reply_topic)).outerjoin(Topic, Reply.reply_topic == Topic.id) \
        .group_by(Topic.topic_title).all()
    print(replies)
    return render_template('category_view.html', topics=topics, category=category, replies=replies)


@conclave.route('/<topic_id>')
def view(topic_id):
    replies = Reply.query.filter_by(reply_topic=topic_id).all()
    topic = Topic.query.filter_by(id=topic_id).first()
    original_author = User.query.filter_by(id=topic.topic_author).first()
    # reply_author = User.query.filter_by(id=replies.reply_author)
    print(f'reply author {replies}')
    return render_template('topic_details.html', topic=topic, replies=replies,
                           op=original_author)


@conclave.route('/add', methods=['GET', 'POST'])
def add():
    form = NewTopicForm(request.form)

    if request.method == 'POST' and form.validate():
        new_topic = Topic(topic_title=form.topic_title.data,
                          topic_content=form.topic_content.data,
                          topic_category=form.topic_category.data,
                          topic_date=datetime.datetime.now(),
                          topic_author=current_user.id)
        db.session.add(new_topic)
        db.session.commit()

        return redirect(url_for('conclave.index'))
    return render_template('new_topic.html', form=form)


@conclave.route('/add_category', methods=['GET', 'POST'])
@login_required
def add_category():
    form = AddCategoryForm(request.form)

    if request.method == 'POST' and form.validate():
        new_category = Category(category_name=form.category_name.data,
                                category_description=form.category_description.data)

        db.session.add(new_category)
        db.session.commit()

        flash('Category Added')
        return redirect(url_for('conclave.index'))
    return render_template('category_add.html', form=form)


@conclave.route('<int:topic_id>/reply', methods=['GET', 'POST'])
def reply(topic_id):
    form = ReplyTopicForm(request.form)
    topic = Topic.query.filter_by(id=topic_id).first()

    if request.method == 'POST' and form.validate():
        new_reply = Reply(reply_content=form.reply_content.data,
                          reply_date=datetime.datetime.now(),
                          reply_topic=topic_id,
                          reply_author=current_user.id)
        db.session.add(new_reply)
        db.session.commit()

        return redirect(url_for('conclave.view', topic_id=topic_id))

    return render_template('topic_reply.html', topic=topic, form=form)


@conclave.route('<int:topic_id>/edit', methods=['GET', 'POST'])
def edit(topic_id):
    topic = Topic.query.get_or_404(topic_id)

    form = EditTopicForm()

    if form.validate_on_submit():
        topic.topic_title = form.topic_title.data
        topic.topic_content = form.topic_content.data

        db.session.commit()
        flash('Topic Updated')
        return redirect(url_for('conclave.view', topic_id=topic_id))

    elif request.method == 'GET':
        form.topic_title.data = topic.topic_title
        form.topic_content.data = topic.topic_content

    return render_template('topic_edit.html', form=form)


@conclave.route('<int:topic_id>/<int:reply_id>/reply_edit', methods=['GET', 'POST'])
def reply_edit(reply_id, topic_id):
    topic_reply = Reply.query.get_or_404(reply_id)
    print(topic_reply.reply_content)

    form = ReplyTopicForm()

    if form.validate_on_submit():
        topic_reply.reply_content = form.reply_content.data
        topic_reply.reply_date = datetime.datetime.now()

        db.session.commit()
        flash('Reply Updated')
        return redirect(url_for('conclave.view', topic_id=topic_id))

    elif request.method == 'GET':
        form.reply_content.data = topic_reply.reply_content

    return render_template('topic_reply_edit.html', form=form)


@conclave.route('/<int:topic_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    db.session.delete(topic)
    db.session.commit()
    flash('Topic Deleted')
    return redirect(url_for('conclave.index'))

src/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/about')
def info():
    return render_template('about.html')

src/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import login_user, login_required, logout_user, current_user
from src import app, db
from src.models import User
from src.users.forms import (LoginForm, RegistrationForm, EditUserForm,
                             UserProfileForm, ChangePasswordForm)
import datetime

users = Blueprint('users', __name__,
                  template_folder='templates/users')


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_email=form.user_email.data).first()
        if user is None or not user.check_password(form.user_password.data):
            flash('Invalid username or password')
            return redirect(url_for('users.login'))
        login_user(user)

        next = request.args.get('next')

        if next == None or not next[0] == '/':
            next = url_for('core.index')

        return redirect(next)
    return render_template('login.html', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(user_email=form.user_email.data,
                    user_username=form.user_username.data,
                    user_password=form.user_password.data,
                    user_role='User',
                    user_date=datetime.datetime.now())
        if form.check_email(form.user_email.data):
            flash('Email already exists')

        elif form.check_username(form.user_username.data):
            flash('username exists')

        else:
            db.session.add(user)
            db.session.commit()
            flash('Thanks for registering!')

            return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users.route('/list')
@login_required
def list():
    users = User.query.all()
    return render_template('list_users.html', users=users)


@users.route('/<int:user_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.user_role != 'Admin':
        abort(403)
    form = EditUserForm()

    if form.validate_on_submit():
        user.user_username = form.user_username.data
        user.user_email = form.user_email.data
        user.user_role = form.user_role.data
        db.session.commit()
        flash('User Updated')
        return redirect(url_for('users.list'))

    elif request.method == 'GET':
        form.user_username.data = user.user_username
        form.user_email.data = user.user_email
        form.user_role.data = user.user_role

    return render_template('edit_user.html', form=form, user_id=user_id)


@users.route('/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.user_role != 'Admin':
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User Deleted')
    return redirect(url_for('users.list'))


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.get_or_404(current_user.id)

    form = UserProfileForm()
    change_pw_form = ChangePasswordForm()

    if form.validate_on_submit():
        user.user_username = form.user_username.data
        user.user_email = form.user_email.data
        user.user_role = form.user_role.data
        user.user_first_name = form.user_first_name.data
        user.user_last_name = form.user_last_name.data
        # user.user_birthday = form.user_birthday.data
        user.user_location = form.user_location.data
        user.user_about = form.user_about.data
        user.user_occupation = form.user_occupation.data
        user.user_interests = form.user_interests.data

        print(form.submit.label)
        db.session.commit()
        flash('profile Updated')
        return redirect(url_for('conclave.index'))

    elif request.method == 'GET':
        form.user_username.data = user.user_username
        form.user_email.data = user.user_email
        form.user_role.data = user.user_role
        form.user_first_name.data = user.user_first_name
        form.user_last_name.data = user.user_last_name
        # form.user_birthday.data = user.user_birthday
        form.user_location.data = user.user_location
        form.user_about.data = user.user_about
        form.user_occupation.data = user.user_occupation
        form.user_interests.data = user.user_interests

    if change_pw_form.validate_on_submit():
        user.user_password = change_pw_form.new_password.data
        db.session.commit()
        flash('Password Changed', 'success')
        return redirect(url_for('users.profile'))

    return render_template('profile_edit.html', form=form, change_pw_form=change_pw_form)

src/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h2>About Us</h2>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="UTF-8" >
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7e51c8576e.js" crossorigin="anonymous"></script>
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('core.index') }}">Conclave</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('conclave.index') }}"><i class="fas fa-users"></i>Main Forum <span class="sr-only">(current)</span></a>
      </li>
      {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.profile') }}"><i class="fas fa-user-shield"></i> My Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('conclave.add') }}"><i class="far fa-plus-square"></i> New Topic</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout') }}" tabindex="-1" aria-disabled="true"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
      {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.login') }}"><i class="fas fa-sign-in-alt"></i> Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.register') }}" ><i class="fas fa-user-plus"></i> Register</a>
          </li>
      {% endif %}
      {% if current_user.user_role == 'Admin' %}
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-tools"></i>
                  Admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a href="{{ url_for('users.list') }}" class="dropdown-item">User Admin</a>
                  <a href="#" class="dropdown-item">Post Admin</a>
                  <a href="{{ url_for('conclave.add_category') }}" class="dropdown-item">Category Admin</a>
              </div>
          </li>
      {% endif %}

    </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control form-control-sm mr-sm-2" type="search" placeholder="Search Disabled" aria-label="Search">
          <button class="btn btn-outline-primary btn-sm my2 my-sm-0 disabled" type="submit">Search</button>
        </form>
  </div>
</nav>
            {% block content %}
            {% endblock %}
    </body>
</html>

src/templates/category_add.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h4>Add Category</h4>
            </div>
            <div class="card-body">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/templates/category_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-title">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{ url_for('conclave.index') }}">Main</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            {{ category }}
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    {% if topics|length > 0 %}
                        {% for topic in topics %}
                            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                <a href="{{ url_for('conclave.view', topic_id=topic.id) }}" class="stretched-link" style="text-decoration: none; font-size: medium;">{{ topic.topic_title }}</a>
                                 {% if replies %}
                                     <span class="badge badge-primary badge-pill">{{ replies[0][1] }}</span>
                                 {% endif %}
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Index</h2>
    </div>
{% endblock %}

src/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {%  with messages = get_flashed_messages() %}
        {% if messages %}
            {%  for message in messages %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h3>Main Forum</h3>
            </div>
            {% for category in categories %}
                <div class="row">
                    <div class="col-sm-9">
                        <div class="card-body">
                            <div class="card" style="padding: 0;">
                                <div class="card-body">
                                    <h5 class="card-title" style="font-size: medium;">
                                        <a href="{{ url_for('conclave.category_view', category_id=category.id) }}" style="text-decoration: none"><h5>{{ category }}</h5></a>
                                    </h5>
                                    <ul class="list-group">
                                        {% for topic in topics %}
                                            {% if topic.topic_category == category.id %}
                                                <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                                    <a href="{{ url_for('conclave.view', topic_id=topic.id) }}" class="stretched-link" style="text-decoration: none; font-size: medium;">{{ topic.topic_title }}</a>
                                                    <span class="badge badge-primary badge-pill">{{ topic.count_1 }}</span>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/templates/new_topic.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h2>New Topic</h2>
            </div>
            <div class="card-body">
                <form method="post">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.topic_title) }}
                    {{ wtf.form_field(form.topic_category) }}
                    {{ wtf.form_field(form.topic_content) }}
                    {{ form.submit(class='btn btn-primary') }}
                </form>
                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

src/templates/topic_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {%  with messages = get_flashed_messages() %}
        {% if messages %}
            {%  for message in messages %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h4>{{ topic.topic_title }}
                    <button title="Delete" class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmDelete">
                        <i class="far fa-trash-alt"></i>
                    </button>
                </h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-2 rounded border border-right">
                        <p class="text-sm-left" style="font-size: smaller; padding:5px;">{{ op.user_username }}</p>
                        <p class="text-sm-left" style="font-size: x-small;">{{ topic.topic_date.strftime('%Y-%m-%d') }}</p>
                    </div>
                    <div class="col-10">
                        <p class="text-muted">{{ topic.topic_content|markdown }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item list-group-item-dark">
                        <a href="{{ url_for('conclave.reply', topic_id=topic.id) }}" class="btn" style="text-decoration: none; font-size: small;"><i class="fas fa-reply"></i> Reply</a>
                    </li>
                    <li class="list-group-item list-group-item-dark">
                        <a href="#" class="btn" style="text-decoration: none; font-size: small;"> <i class="far fa-comment-dots"></i> Quote</a>
                    </li>
                    {% if current_user.id == topic.topic_author %}
                        <li class="list-group-item list-group-item-dark">
                            <a href="{{ url_for('conclave.edit', topic_id=topic.id) }}" class="btn" style="text-decoration: none; font-size: small;"><i class="fas fa-edit"></i>Edit</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <br>
        {% for reply in replies %}
            <div class="card">
                <div class="card-body">
                     <p class="text-muted">{{ reply.reply_content|markdown }}</p>
                </div>
            <div class="card-footer">
                <ul class="list-group list-group-horizontal">
                    {% if current_user.id == reply.reply_author %}
                        <li class="list-group-item list-group-item-dark">
                            <a href="{{ url_for('conclave.reply_edit', reply_id=reply.id, topic_id=topic.id) }}" class="btn" style="text-decoration: none; font-size: small;"><i class="fas fa-edit"></i>Edit</a>
                        </li>
                        <li class="list-group-item list-group-item-dark">
                            <a href="#" class="btn" style="text-decoration: none; font-size: small;"><i class="far fa-trash-alt"></i> Delete</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            </div>
            <br>
        {% endfor %}
    </div>
    <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labeledby="confirmDeleteLabel" aria-hidden="true" >
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmDeleteLabel">
                            Confirm Delete
                        </h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Delete {{ topic.topic_title }}? This cannot be undone.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{{ url_for('conclave.delete', topic_id=topic.id) }}">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

src/templates/topic_edit.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h4>Edit Topic</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {{ wtf.quick_form(form) }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/topic_reply.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}
{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                {{ topic.topic_title }}
            </div>
            <div class="card-body">
                {{ topic.topic_content|markdown }}
            </div>
        </div><br>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.reply_content) }}
                {{ form.submit(class='btn btn-primary btn-sm') }}
            </form>
        </div>
    </div>

    </div>
{% endblock %}

src/templates/topic_reply_edit.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h4>Edit Reply</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.reply_content) }}
                    <button class="btn btn-primary" type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}