src/users/templates/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import login_user, login_required, logout_user, current_user
from src import app, db
from src.models import User
from src.users.forms import LoginForm, RegistrationForm, EditUserForm
import datetime

users_blueprint = Blueprint('users', __name__,
                            template_folder='templates/users')


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_email=form.user_email.data).first()

        if user.check_password(form.user_password.data) and user is not None:

            login_user(user)

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('index')

            return redirect(next)
    return render_template('login.html', form=form)


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(user_email=form.user_email.data,
                    user_username=form.user_username.data,
                    user_password=form.user_password.data,
                    user_role='User',
                    user_date=datetime.datetime.now())
        if form.check_email(form.user_email.data):
            flash('Email already exists')

        elif form.check_username(form.user_username.data):
            flash('username exists')

        else:
            db.session.add(user)
            db.session.commit()
            flash('Thanks for registering!')

            return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users_blueprint.route('/profile')
@login_required
def profile():
    user = User.query.filter_by(id=current_user.id).first()
    return render_template('profile_edit.html', user=user)


@users_blueprint.route('/list')
@login_required
def list():
    users = User.query.all()
    return render_template('list_users.html', users=users)


@users_blueprint.route('/<int:user_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(user_id):

    user = User.query.get_or_404(user_id)
    if current_user.user_role != 'Admin':
        abort(403)
    form = EditUserForm()

    if form.validate_on_submit():
        user.user_username = form.user_username.data
        user.user_email = form.user_email.data
        user.user_role = form.user_role.data
        user.user_password = form.user_password.data
        print(form.submit.label)
        db.session.commit()
        flash('User Updated')
        return redirect(url_for('users.list'))

    elif request.method == 'GET':
        form.user_username.data = user.user_username
        form.user_email.data = user.user_email
        form.user_role.data = user.user_role

    return render_template('edit_user.html', form=form, user_id=user_id)


@users_blueprint.route('/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(user_id):

    user = User.query.get_or_404(user_id)
    if current_user.user_role != 'Admin':
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User Deleted')
    return redirect(url_for('users.list'))


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

src/users/templates/users/edit_user.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
       <div class="container" style="margin-top: 15px;">
            <div class="card">
                <div class="card-header">
                    <h4>{{ form.user_username.data|capitalize }}
                         <button title="Delete" class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmDelete">
                            <i class="far fa-trash-alt"></i>
                        </button>
                     </h4>
                </div>
                </div>
                <div class="card-body">
                  <form method="post">
                    {{ wtf.quick_form(form) }}
                  </form>
                </div>
            </div>
        <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labeledby="confirmDeleteLabel" aria-hidden="true" >
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmDeleteLabel">
                            Confirm Delete
                        </h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Delete {{ form.user_username.data }}? This cannot be undone.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{{ url_for('users.delete', user_id=user_id) }}">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}

src/users/templates/users/list_users.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 15px;">
        {%  with messages = get_flashed_messages() %}
        {% if messages %}
            {%  for message in messages %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <ul class="list-group">
            {% for user in users %}
                <li class="list-group-item">
                    {{ user.user_username }}
                    <p class="text-muted" style="font-size: 12px;">{{ user.user_role }}</p>
                    <a href="{{ url_for('users.edit', user_id=user.id) }}">
                        <button class="btn btn-outline-primary btn-sm">
                            <i class="far fa-edit"></i>
                        </button>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

src/users/templates/users/login.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    {%  with messages = get_flashed_messages() %}
        {% if messages %}
            {%  for message in messages %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="card w-75 mx-auto" style="margin-top: 15px;">
        <div class="card-header">
            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        </div>
        <div class="card-body">
            <div class="form-group">
                <form class="form-signin" method="post">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.user_email) }}
                    {{ wtf.form_field(form.user_password) }}
                    {{ form.submit(class='btn btn-primary') }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% import '/bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
    {%  with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {%  for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <div class="card" style="margin-top: 25px;">
            <div class="card-header">
                <h4>My Profile</h4>
                <button class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#changePassword">
                    Change Password
                </button>
            </div>
            <div class="card-body">
                <form method="post">
                    {{ wtf.quick_form(form) }}
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="changePassword" tabindex="-1" role="dialog" aria-labelledby="changePasswordLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Change Password</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form method="post">
                  <div class="form-group">
                      {{ wtf.quick_form(change_pw_form) }}
                  </div>
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

src/users/templates/users/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
     {%  with messages = get_flashed_messages() %}
        {% if messages %}
            {%  for message in messages %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="jumbotron">
        <form method="post" style="width: 50rem;">
            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.user_username) }}
            {{ wtf.form_field(form.user_email) }}
            {{ wtf.form_field(form.user_password) }}
            {{ wtf.form_field(form.pass_confirm) }}
            {{ form.submit(class='btn btn-primary') }}
        </form>
    </div>
{% endblock %}